### ISSUE TITLE
Compatability with TB60

### ISSUE THREAD

**Issue by bonanza123** [tjeb/Mailbox-Alert#1]
TB 60 (the current beta) reports incompatibility with this awesome plugin.
I'm not sure whether this affects real functionality or is just a heads-up that some compatibility flag needs to be set.

**Comment by bastien30** [comment]
Thunderbird 60 is stable now, but Mailbox Alert seems not working anymore.

An update would be awsome :grin:

**Comment by bonanza123** [comment]
Just for the record, I manually bumped the maxversion in the RDF and its working fine so far. But I didn't do a thorough test though.

**Comment by bastien30** [comment]
Yes you're right it seems to works fine for the default popup and sound, but not with the command option :

> [MailboxAlert] error at chrome://mailboxalert/content/mailboxalert_funcs.js:548: TypeError: Components.classes['@mozilla.org/intl/saveascharset;1'] is undefined

**Comment by dodmi** [comment]
I can confirm, that Popups are working fine, but executing external commands fails.
Please make this great addon compatible :)

**Comment by bastien30** [comment]
Mailbox-Alert v0.18 has been released with TB60+ compatibility.
The extension is not yet up to date on AMO but you can download it from the official website : https://tjeb.nl/Projects/Mailbox_Alert/mailboxalert-0.18.xpi

I confirm that external commands works fine now :smiley:

Thanks to the author !
