### ISSUE TITLE
minor problem with white on black

### ISSUE THREAD

**Issue by gooly** [tjeb/Mailbox-Alert#10]
I am using the theme "TT DeepDark 12.1.3" and the 2nd field popup doesn't show anything :(
Here you see what I see: https://ufile.io/l5w13kj0
But thanks a lot for this app!!

**Comment by tjeb** [comment]
If I ever have time to work on features again I will consider taking another shot at making colors configurable, but unfortunately that probably won't be anytime soon. The best workaround I can think of is have an external tool to show popups and call that instead of the built-in one.
