### ISSUE TITLE
thunderbird linux: cannot handle command arguments containing umlaut in path

### ISSUE THREAD

**Issue by bits-fritz** [tjeb/Mailbox-Alert#12]
Execute a command does not accept path arguments containing umlauts.
Here I've uploded examle (sound) files I get played with "aplay" which should be installed on any sound capable linux system.
https://bits-fritz.de/File/bug/tunes.zip (append at this issue didn't work)
successful command:
/usr/bin/aplay [wherever]/toene/mail.wav
"test configuration" plays sound
unsuccessful command:
/usr/bin/aplay [wherever]/toene/trööt.wav
"test configuration" silently ignores the command

Mailbox Alert 0.22.1
Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.9.0

**Comment by tjeb** [comment]
I tried on my Debian system with a wav with the name trööt, and it seems to work here, so I'm not quite sure what goes wrong there...

**Comment by bits-fritz** [comment]
It appears, that it is the same behaviour when the path doesn't exist.
I opened the tools -> developer tools -> failure console[0]: 
[0]sorry no english interface at hand
3 Examples
====== successful sound played (path is valid) ==================
[MailboxAlert] run() called
[MailboxAlert] command now: /usr/bin/play /home/frieder/arbeit/wueste-welle/ww-ringtone/wueste_welle-rington.opus
[MailboxAlert] Command to execute: 
[MailboxAlert] /usr/bin/play /home/frieder/arbeit/wueste-welle/ww-ringtone/wueste_welle-rington.opus
[MailboxAlert] 
[MailboxAlert] Executable: 
[MailboxAlert] /usr/bin/play
[MailboxAlert] 
[MailboxAlert] Command:  /usr/bin/play
[MailboxAlert] Arguments: /home/frieder/arbeit/wueste-welle/ww-ringtone/wueste_welle-rington.opus # path is valid
====== /successful sound played ==================

============= no sound (path is valid) =============
[MailboxAlert] run() called
[MailboxAlert] command now: /usr/bin/play /home/frieder/arbeit/wueste-welle/ww-ringtone/wüste_welle-rington.opus
[MailboxAlert] Command to execute: 
[MailboxAlert] /usr/bin/play /home/frieder/arbeit/wueste-welle/ww-ringtone/wüste_welle-rington.opus
[MailboxAlert] 
[MailboxAlert] Executable: 
[MailboxAlert] /usr/bin/play
[MailboxAlert] 
[MailboxAlert] Command:  /usr/bin/play
[MailboxAlert] Arguments: /home/frieder/arbeit/wueste-welle/ww-ringtone/wüste_welle-rington.opus # path is valid
============= /no sound =============


============= no sound (path is invalid) =============
[MailboxAlert] run() called
[MailboxAlert] command now: /usr/bin/play /home/frieder/arbeit/wueste-welle/ww-ringtone/wüste_welle-rington
[MailboxAlert] Command to execute: 
[MailboxAlert] /usr/bin/play /home/frieder/arbeit/wueste-welle/ww-ringtone/wüste_welle-rington
[MailboxAlert] 
[MailboxAlert] Executable: 
[MailboxAlert] /usr/bin/play
[MailboxAlert] 
[MailboxAlert] Command:  /usr/bin/play
[MailboxAlert] Arguments: /home/frieder/arbeit/wueste-welle/ww-ringtone/wüste_welle-rington # path is invalid
============= /no sound =============

**Comment by tjeb** [comment]
This may be related to #22

**Comment by tjeb** [comment]
I think I have found a workaround internally. With the patch I just committed it pretends that the encoding of the arguments is UTF-16. This isn't the case, but it does make TB convert it to UTF-8 internally, just before execution. Unless I can think of a better way to do this, this will be in the next release.
