### ISSUE TITLE
[FR] Mail alert if mail is NOT incoming?

### ISSUE THREAD

**Issue by PeterCodar** [tjeb/Mailbox-Alert#14]
I get a lot of automated status mails every day. It would be great if I could set an alert if a mail from a specific sender has NOT been received until a specific time (let's say mail from sender X expected until 11.00 AM is not incoming = alert "sender x overdue").

Do you think such a reverse logic is possible?

**Comment by tjeb** [comment]
Mailbox Alert cannot do that (as you probably have seen).

It seems possible to build such a thing (how to let the user tell the system what to check for seems the hardest part), but I have no plans to add something like that to Mailbox Alert.
