### ISSUE TITLE
%server in custom command does not work any longer (TB 68)

### ISSUE THREAD

**Issue by jolange** [tjeb/Mailbox-Alert#15]
Since TB was updated to 68.2.1, using `%server` in my custom command does no longer work. I pass it to `notify-send` and no notification is shown at all.

For debugging, I used this command:
```
/usr/bin/notify-send "%server" "%sendername" -t 100000
```

No notification is shown and the error console says:

```
[MailboxAlert] Command to execute: 
[MailboxAlert] /usr/bin/notify-send "%server" "%sendername" -t 100000
[MailboxAlert] 
[MailboxAlert] Executable: 
[MailboxAlert] /usr/bin/notify-send
[MailboxAlert] 
[MailboxAlert] Command:  /usr/bin/notify-send
[MailboxAlert] Arguments: ,Johannes Lange ,-t,100000
```

On the other hand, using the "Test these settings" works (it shows "SomeServer").

There seems to be a problem with the `%server` field. If I don't use it, it works:

```
/usr/bin/notify-send "TEST" "%sendername" -t 100000
```

Do you have an idea what happened in TB that might cause this?

**Comment by rnc** [comment]
I am also seeing this and the fact the `%*folder` macros are also undefined.

**Comment by rnc** [comment]
Thanks! 
@tjeb has the new release been submitted to the add-ons site? Or where can we get it please?

**Comment by tjeb** [comment]
I submitted it but it did not pass review due to a builder script ending up in the xpi somehow. Resubmitted now, it should be on the addons site shortly.

**Comment by jolange** [comment]
@tjeb thanks for fixing this so quickly!

I still don't see the updated version on the mozilla site, though.

I packaged this on my own for now and simplified the build script a bit, maybe you like it: #17
