### ISSUE TITLE
Exclusions

### ISSUE THREAD

**Issue by rnc** [tjeb/Mailbox-Alert#21]
While I can see 

`Don't let parent folders alert for this one`

its not clear whether it operates recursively i.e. don't do alerts on child folders as well? Or, if not, could that be added as an option?

**Comment by tjeb** [comment]
Cleaning up old issues on github, sorry for not responding earlier.

If an folder has the 'Don't let parent folders alert' set, it will also stop its children's alerts from bubbling up.
