### ISSUE TITLE
Version 0.24 doesn't work in TB 75.0b3

### ISSUE THREAD

**Issue by jph108** [tjeb/Mailbox-Alert#23]
Hello,
I have installed Version 0.24 in TB version 75.0b3, and when I right-click on a folder, I don't see the Mailbox alert menu item. I'm running Mac OS Catalina (10.15.4). 
With Best Regards,
Josh

**Comment by voffkan** [comment]
Hi. Same problem, no items appear in the context menu.
Mac OS Catalina 10.15.6
Thunderbird 78.1.1.
add-on Version 0.24

Install add-on:
1598195576042	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Warning processing legacy: An unexpected property was found in the WebExtension manifest.
1598195576117	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Warning processing legacy: An unexpected property was found in the WebExtension manifest.
1598195582444	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Warning processing legacy: An unexpected property was found in the WebExtension manifest.

Enable add-on
1598195582446	addons.webextension.{9c21158b-2c76-4d0a-980a-c51fc9cefaa7}	WARN	Loading extension '{9c21158b-2c76-4d0a-980a-c51fc9cefaa7}': Reading manifest: Warning processing legacy: An unexpected property was found in the WebExtension manifest.

**Comment by tjeb** [comment]
Yes, like most extensions, Mailbox Alert does not work with versions later than 68. Updating for later versions requires a full rewrite, as the internal API's that is used have been changed or removed completely. It is currently not even known if all functionality can be reproduced. I have been working on figuring out what can be and how to do it, but this is a lot of work, so a version that works with later thunderbird versions is quite some time away.

**Comment by tjeb** [comment]
Forgot to close this, but if it was still in your extensions list, it should have updated by now; as of MA 0.25, it is compatible with Thunderbird 78.
