### ISSUE TITLE
command execution not working

### ISSUE THREAD

**Issue by regragui-cobra** [tjeb/Mailbox-Alert#24]
OS: Ubuntu Mate 18.04
Steps:

Test1: 
1-activating use of command with letting command field blank
2-click on Test these settings

Error1: [MailboxAlert] error at chrome://mailboxalert/content/mailboxalert_funcs.js:637: ReferenceError: Services is not defined

Test2:
1-activating use of command with command being play "/path/to/file.wav" (command working on terninal)
2-click on Test these settings

Error2: [MailboxAlert] error at chrome://mailboxalert/content/mailboxalert_funcs.js:637: ReferenceError: Services is not defined

**Comment by areographe** [comment]
Hey, I'm experiencing this same issue. Thunderbird 68.12.0 (64-bit) on Manjaro Cinnamon, kernel 5.9.1.

**Comment by tjeb** [comment]
That's... interesting, as Services is used in more places, and is according to the docs.

A small bright note is that the error that you get is actually in trying to get the i18n string to show the real error, so one thing you can try is to provide the full path to the executable (e.g. /usr/bin/play).

I will look into fixing this. However, newer versions of Mailbox Alert will not be compatible with Thunderbird 68 anymore, there's simply too much differences with 78.

**Comment by tjeb** [comment]
Fixed in commit 6f4c6ae2, will be in next release.
