### ISSUE TITLE
Not able to browse for custom sounds in linux Fedora 28

### ISSUE THREAD

**Issue by larieu** [tjeb/Mailbox-Alert#4]
it seems to wor with default sound

unfortunately clicking on "Browse" has no effect
I have tried to put the short path ( from the user home root ~/rest_of_the_path/file.wav) and no effect 
It works with the full path (/home/username/rest_of_the_path/file.wav )
It will be grat to fix the browse button

**Comment by tjeb** [comment]
The API had changed on me; I've just uploaded 0.19. When it has been reviewed and published, can you check if this fixes it for you?

**Comment by blue-bullet** [comment]
Browse still has no effect on message filters.  Additionally one cannot type in the input box to the left
of the Browse Folder push button.  In the absence of Browse that's where one would type in the path to file.

Running KDE Neon 5.15, Kernel: 4.15.0-50-generic x86_64 bits: 64 Desktop: KDE Plasma 5.15.5

**Comment by tjeb** [comment]
Cleaning up old issues for old versions, if this is still an issue, please re-open or submit a new one.
