### ISSUE TITLE
Impossible to use cusom icon in alerts

### ISSUE THREAD

**Issue by gogaxxx** [tjeb/Mailbox-Alert#5]
1. Select "Edit Mailbox Alert alerts"
2. For icon press "Browse"
3. Select a picture.
4. Press "OK", dialog closes.
5. When mail arrives, the alert is without any icon. Icon disappeares in editor too. 100% reproducible.

I'm using Mailbox Alert 0.18.0 on Thunderbird 52.9.1 (32-bit) under Windows 10

**Comment by tjeb** [comment]
what kind of image file? Perhaps mozilla has issues rendering it; it seems to work for me with small png files.

**Comment by gogaxxx** [comment]
Any image, I've tried png, jpg and gif.
Actually, it displays OK when you select it and try in test mode, but when real mail arrives it is gone.

**Comment by tjeb** [comment]
Cleaning up long-standing issues for old versions. If this is still an issue, please re-open or create another ticket.
