### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by solsticesurfer** [tjeb/Mailbox-Alert#6]
I'm using the TT DeepDark theme for Thunderbird. Due to its CSS, it causes the alert that pops up to have white text on a white background. Is it possible to change the text colors used in the alert popup? I've tried modifying the newmailalert.css file but can't get anything to change when I use the test option.

**Comment by solsticesurfer** [comment]
Figured it out. I was editing the correct style sheet but wasn't rebuilding the mailboxalert.jar properly. Now I have a proper jar and the customization works.

**Comment by solsticesurfer** [comment]
Re-opening this. Manually editing the stylesheet isn't ideal because the changes are wiped out when an update is pushed. 

So, please consider adding an option to override the fore/background colors

**Comment by StayPirate** [comment]
@tjeb any chance to merge #30??
