### ISSUE TITLE
Help button: TypeError: protocolSvc.loadUrl

### ISSUE THREAD

**Issue by JohannesBuchner** [tjeb/Mailbox-Alert#7]
When pressing the "Help" button, I get the following error printed:

JavaScript error: chrome://mailboxalert/content/alert_list.xul, line 32: TypeError: protocolSvc.loadUrl is not a function

Thunderbird 60.3.1, Mailbox Alert 0.18.0

**Comment by tjeb** [comment]
is this still an issue? It seems to work for me

**Comment by JohannesBuchner** [comment]
confirming, WFM
