### ISSUE TITLE
Custom .wav Crashes Thunderbird

### ISSUE THREAD

**Issue by tstrm** [tjeb/Mailbox-Alert#8]
Using Windows 10 and Thunderbird 60.3.3, if I enter a path to a custom .wav file, Thunderbird crashes when I try to test it.  Also the Browse button doesn't work properly as stated in issue #4 .  It pops up an error dialog saying, "Error, unable to find selected audio file. Using default."
![image](https://user-images.githubusercontent.com/45966456/50149055-ba3a5d00-027f-11e9-8b6d-3b5b7f57f0d6.png)

**Comment by MoneyAllDay** [comment]
Same here.

Mailbox Alert 0.18.0
Thunderbird 60.4.0
Windows 10 x64

**Comment by tjeb** [comment]
The playing of the wav is and internal function in TB, and an extension should not be able to fully crash thunderbird. I have tested it with some local wavs and those seem to work fine. Can you perhaps share the wav that crashes it?

I have removed the error popup though.

**Comment by MoneyAllDay** [comment]
@tstrm 

I think the problem might be the length of the audio file because i reduced from 6secs to 5secs and it no longer crashes Thunderbird.
